import "./globals.css";
import { StateContext } from "../hook/StateContext";
import { AntdRegistry } from "@ant-design/nextjs-registry";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AntdRegistry>
          <StateContext>{children}</StateContext>
        </AntdRegistry>
      </body>
    </html>
  );
}
